<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StoryWeaver.Core\StoryWeaver.Core.csproj" />
    <ProjectReference Include="..\StoryWeaver.Llm\StoryWeaver.Llm.csproj" />
    <ProjectReference Include="..\StoryWeaver.Storage\StoryWeaver.Storage.csproj" />
    <ProjectReference Include="..\StoryWeaver.App\StoryWeaver.App.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
